FROM python:3.6

LABEL vendor="NexusLab"
LABEL version="1.0.0"
LABEL description="EZSetup Cloud Worker"

WORKDIR /var/www/
COPY . /var/www

RUN pip install pipenv
RUN pipenv install --system --deploy

CMD ["rq", "worker", "-c", "backgroundjobs.settings"]
